name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: 1.19
      - run: go version

      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Examine source code
        run: go vet -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        if: github.event_name == 'push'
        env:
          TEST_ENV_URL: ${{ secrets.TEST_ENV_URL }}
          TEST_INDEX_HTML_URL: ${{ secrets.TEST_INDEX_HTML_URL }}
          TEST_SENTRY_DSN: ${{ secrets.TEST_SENTRY_DSN }}
        run: go test -v -cover -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        run: bash <(curl -s https://codecov.io/bash)

      - name: Update Go report card
        if: github.event_name == 'push'
        uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9 # v1.0
